=== fpbattaglia/nitro/test/deviceinterface.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://ubixum.com/deviceinterface/"           
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"           
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xi="http://www.w3.org/2001/XInclude"            
	   xsi:schemaLocation="http://www.w3.org/2001/XMLSchema 
	   		       http://www.w3.org/2001/XMLSchema.xsd"
	   xmlns="http://ubixum.com/deviceinterface/">

  <xs:import namespace="http://www.w3.org/2001/XInclude" schemaLocation="http://www.w3.org/2001/XInclude.xsd" />
       
  <xs:element name="deviceinterface">
   <xs:annotation>
       <xs:documentation>
        A devide interface element contains a collection of terminals.
       </xs:documentation>
   </xs:annotation>
   <xs:complexType>
    <xs:sequence>
      <xs:element maxOccurs="unbounded" minOccurs="0" ref="terminal" />
      <xs:element maxOccurs="unbounded" minOccurs="0" ref="xi:include" />
    </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:attributeGroup name="nodeAttributes">     
    <xs:attribute name="name" type="nameType" use="required"/>
    <xs:attribute name="addr" type="addrType" use="optional"/>    
  </xs:attributeGroup>

  <xs:element name="terminal">
    <xs:complexType>      
      <xs:sequence>
        <xs:element ref="comment" minOccurs="0" maxOccurs="1" />
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="register"/>        
      </xs:sequence>
      <xs:attributeGroup ref="nodeAttributes"/>
      <xs:attribute name="regDataWidth" type="xs:positiveInteger" use="required"/>
      <xs:attribute name="regAddrWidth" type="xs:nonNegativeInteger" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="register">
    <xs:complexType>
              
          <xs:sequence>
            <xs:element ref="comment" minOccurs="0" maxOccurs="1" />
            <xs:element ref="type" />
            <xs:element ref="mode"/>            
           <xs:choice>
              <xs:sequence>                                          
                    <xs:element ref="width"/>    
                    <xs:element ref="init" minOccurs="0"/>    
                    <xs:element ref="array" minOccurs="0"/>    
                    <xs:element ref="valuemap" minOccurs="0"/>                  
              </xs:sequence>

              <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="subregister" minOccurs="2" />
              </xs:sequence>
            </xs:choice>
            
            
          </xs:sequence>


      <xs:attributeGroup ref="nodeAttributes"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="subregister">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="comment" minOccurs="0" maxOccurs="1" />
        <xs:element ref="width"/>
        <xs:element ref="init" minOccurs="0" />
        <xs:element minOccurs="0" ref="valuemap"/>
        
      </xs:sequence>
      <xs:attribute name="name" type="nameType" />      
    </xs:complexType>
  </xs:element>
  
  
	<xs:simpleType name="nameType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[_A-Za-z0-9]+" />
		</xs:restriction>
	</xs:simpleType>
    <xs:simpleType name="addrType">
        <xs:restriction base="xs:integer" >
            <xs:minInclusive value="0" />
        </xs:restriction>
    </xs:simpleType>

  <xs:element name="mode">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="write"/>
        <xs:enumeration value="read"/>
        <xs:whiteSpace value="collapse" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  
  <xs:element name="type">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:enumeration value="int" />
            <xs:enumeration value="trigger" />
            <xs:whiteSpace value="collapse" />
        </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="width" type="xs:positiveInteger" />
  <xs:element name="comment" type="xs:string" />
  <xs:element name="init" type="xs:string" />  
  <xs:element name="array" type="xs:positiveInteger" />
  <xs:element name="entry">
    <xs:complexType>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="value" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="valuemap">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="1" ref="entry" />        
      </xs:sequence>      
    </xs:complexType>
    <xs:unique name="uniqueName">
      <xs:selector xpath="entry" />
      <xs:field xpath="@name" />
    </xs:unique>
  </xs:element>
</xs:schema>

=== fpbattaglia/nitro/test/dev.xml
<deviceinterface
	xmlns="http://ubixum.com/deviceinterface/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://ubixum.com/deviceinterface/ deviceinterface.xsd">
	<terminal
		name="Terminal1"
		regAddrWidth="5"
		regDataWidth="5"
		addr="0">
		<register
            name="reg1"
            addr="0">
            <type>int</type>
            <mode>write
            </mode>
            <width>18</width> <!-- bigger than regDataWidth -->
            <init>0</init>
            <array>1</array>
            <valuemap>
                <entry name="evens" value="174762" /> <!-- 2AAAA -->
                <entry name="odds" value="87381" /> <!-- 15555 -->
            </valuemap>
        </register>
        <register
            name="reg2">
            <type>int</type>
            <mode>write</mode>
            <subregister
                name="sub1">
                <width>3</width>
                </subregister>
            <subregister
                name="sub2">
                <width>3</width>
                <valuemap>
                    <entry name="7" value="7" />
                    <entry name="6" value="6" />
                </valuemap>
                </subregister>
       </register>
       <!-- 20 sets of 3 bits -->
       <register
         name="array_reg1">
         <type>int</type>
         <mode>write</mode>
         <width>3</width>
         <array>20</array>
       </register>

       <!-- 4 sets of 7 bits -->
       <register
         name="array_reg2">
         <type>int</type>
         <mode>write</mode>
         <width>7</width>
         <array>4</array>
       </register>

       <!-- 3 sets of 18 bits -->
       <register
        name="array_reg3">
         <type>int</type>
         <mode>write</mode>
         <width>18</width>
         <array>3</array>
       </register>

    </terminal>
    <terminal
        name="int_term"
        regAddrWidth="16"
        regDataWidth="16">
        <register 
            name="int">
            <type>int</type>
            <mode>write</mode>
            <subregister
                name="lw">
                <width>16</width>
                </subregister>
            <subregister
                name="hw">
                <width>16</width>
                </subregister>
        </register>
            
        <register
            name="wide_reg">
            <type>int</type>
            <mode>write</mode>
            <subregister
                name="big_sub1">
                <width>37</width>
                </subregister>
            <subregister
                name="big_sub2">
                <width>4</width>
                </subregister>
            <subregister
                name="big_sub3">
                <width>33</width>
                </subregister>
          </register>
        <!-- Models an actual subregister that had some problems -->
        <register
            name="many_subregs">
            <type>int</type>
            <mode>write</mode>
            <subregister
                name="one">
                <width>8</width>
            </subregister>
            <subregister
                name="two">
                <width>8</width>
            </subregister>
            <subregister
                name="three">
                <width>8</width>
            </subregister>
            <subregister
                name="four">
                <width>8</width>
            </subregister>
            <subregister
                name="five">
                <width>8</width>
            </subregister>
            <subregister
                name="six">
                <width>8</width>
            </subregister>
            <subregister
                name="seven">
                <width>4</width>
            </subregister>
            <subregister
                name="eight">
                <width>12</width>
            </subregister>
            <subregister
                name="nine">
                <width>12</width>
            </subregister>
            <subregister
                name="ten">
                <width>12</width>
            </subregister>
            <subregister
                name="eleven">
                <width>12</width>
            </subregister>
            <subregister
                name="twelve">
                <width>12</width>
            </subregister>
            <subregister
                name="thirteen">
                <width>12</width>
            </subregister>
            <subregister
                name="fourteen">
                <width>12</width>
            </subregister>
            <subregister
                name="fifteen">
                <width>12</width>
            </subregister>
            <subregister
                name="sixteen">
                <width>12</width>
            </subregister>
            <subregister
                name="seventeen">
                <width>12</width>
            </subregister>
            <subregister
                name="eighteen">
                <width>12</width>
            </subregister>
        </register>

    </terminal>
    <terminal
        name="narrow_term"
        regAddrWidth="8"
        regDataWidth="8">
    </terminal>

</deviceinterface>

=== fpbattaglia/nitro/test/test.xml
<deviceinterface
	xmlns="http://ubixum.com/deviceinterface/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://ubixum.com/deviceinterface/ deviceinterface.xsd">
	
	<terminal
		name="Terminal1"
		regAddrWidth="16"
		regDataWidth="16"
		addr="3">
		<register
            name="reg1"
            addr="0">
            <type>int</type>
            <mode>write
            </mode>            
            <width>18</width> <!-- bigger than regDataWidth -->
            <init>0</init>
            <array>1</array>
        </register>
        <register name="addr2reg"> <!-- addr becomes 2 because reg1 width -->
            <comment><![CDATA[cOMMENTS can Have 0x25 all & kinds of ></ special " characters!@]]></comment>
            <type>int</type>
            <mode>write</mode>
            
            <width>3</width>
        </register>
        <register 
            name="reg2" addr="23">
            <type>trigger</type>
            <mode>write</mode>
            <width>1</width>
        </register>
        <register name="reg3">
            <type>int</type>
            <mode>  read </mode> <!-- width should be 3 -->
                                 <!-- addr should be 24 -->
            <subregister name="subreg1">
                <width>2</width>                
            </subregister>
            <subregister name="subreg2">
                <width>1</width>
                <valuemap>
                    <entry name="ON" value="0" />
                    <entry name="OFF" value="1" />
                </valuemap>
            </subregister>
        </register>
	</terminal>
    <terminal
        name="term2"
        regAddrWidth="16"
        regDataWidth="16"
        > <!-- addr should be 4 -->
    </terminal>

    <terminal
        name="array_term"
        regDataWidth="5"
        regAddrWidth="5">
        <!-- array 5 total width 15 -->
        <register
            name="array1">
            <type>int</type>
            <mode>write</mode>
            <width>3</width>
            <array>5</array>
        </register>
        <register
            name="array2">
            <type>int</type>
            <mode>write</mode>             
            <width>32</width>
            <init>1, 2, 34567891011121314, four, 5</init>
            <array>5</array>
            <valuemap>
                 <entry name="four" value="4" />
            </valuemap>
        </register>
 
    </terminal>

    
</deviceinterface>
